parameters:
#    ymc_how_to_acl.example.class: Ymc\HowToAclBundle\Example

services:
#    ymc_how_to_acl.example:
#        class: %ymc_how_to_acl.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
